config/routes.rb
Rails.application.routes.draw do
  resources :sites
  devise_for :users
  root 'sites#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sites
  # GET /sites.json
  def index
    @sites = current_user.sites.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = current_user.sites.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = current_user.sites.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = current_user.sites.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:title, :url, :checker, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webchecker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: 'ex : Amazon' %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, placeholder: 'ex : https://amazon.fr' %>
  </div>
  <div class="field">
    <%= f.label :checker %><br>
    <%= f.text_area :checker, placeholder: 'Une phrase ou un bout de code sensé être dans la page chargée', style: 'height: 60px' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, placeholder: 'Vous pouvez par exemple indiquer les mot de passe et accès au site au cas où', style: 'height: 100px' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<meta http-equiv="refresh" content="300;">
<p id="notice"><%= notice %></p>
<table>
  <tbody>
    <% @sites.each do |site| %>
      <tr height="20">
        <td width="100" class="site" data-url="<%= site.url %>" data-checker="<%= site.checker %>"></td>
        <td><%= site.title %></td>
        <td><%= link_to 'Voir', site %></td>
        <td><%= link_to 'Modifier', edit_site_path(site) %></td>
        <td><%= link_to 'Supprimer', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Rajouter un site', new_site_path %>

app/views/sites/new.html.erb
<h1>Nouveau site</h1>

<%= render 'form' %>

<%= link_to 'Retour à la liste', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @site.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @site.url %>
</p>

<p>
  <strong>Checker:</strong>
  <%= @site.checker %>
</p>

<p>
  <strong>Description:</strong>
  <%= @site.description %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>